name: Python package

on: [push]

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - run: |
        python -m pip install -U pip wheel
        python -m pip install -r requirements-ci.txt
    - run: python -m black . --check
    - run: python -m isort . --check-only
    - run: python -m flake8 .
    - run: python -m bandit . --recursive -c pyproject.toml

  test:
    needs: lint
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - run: |
        python -m pip install -U pip wheel
        python -m pip install .[test]
    - run: |
        python -OO -m unittest discover -s tests

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - run: |
        python -m pip install -U build wheel
        python -m build .
    - uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
